name: Daily Sales Data Update

on:
  schedule:
    - cron: '0 0 * * *'  # Todos los días a medianoche UTC
  workflow_dispatch:      # Permite ejecutar manualmente también

jobs:
  generate-csv:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          pip install pandas numpy

      # 4️⃣ Ejecutar el script para generar CSV
      - name: Generate CSV
        run: python scripts/generate_data.py

      # 5️⃣ Hacer commit y push del CSV generado
      - name: Commit and Push ventas.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ventas.csv
          git commit -m "Update ventas.csv [skip ci]" || echo "No changes to commit"
          git push
